Collection Plugin Updates
DiscipleTools/disciple-tools-survey-collection pull request #8
Opened 2022-11-14 16:29 UTC by kodinkat

- fixes #3 
- fixes #4 
- fixes #5 
  - Unable to recreate...
- fixes #6 
- fixes #7 
- fixes #9

2022-11-15 10:27 UTC, kodinkat commented
@corsacca review ready!

2022-11-16 12:15 UTC, corsacca requested changes

2022-11-16 12:15 UTC, corsacca commented on admin/config-required-plugins.php
> +            'name'     => 'iThemes Security',
@kodinkat not needed

2022-11-16 12:15 UTC, corsacca commented on admin/config-required-plugins.php
> +            'name'     => 'Disciple.Tools Multisite Helper',
Not needed

2022-11-16 12:15 UTC, corsacca commented on magic-link/magic-link-user-app.php
> +                            console.log(data);
log

2022-11-16 12:17 UTC, corsacca commented
With plugin disabled:
![image](https://user-images.githubusercontent.com/24901539/202178470-4504c32f-e3fc-405f-bbee-22d93424f238.png)

2022-11-16 12:50 UTC, corsacca commented on magic-link/magic-link-user-app.php
> +                            console.log(data);
@kodinkat this one? Just no need consoling extra data.

2022-11-16 14:14 UTC, corsacca approved these changes

2022-11-16 14:14 UTC, merged

2022-11-16 14:15 UTC, corsacca commented
thanks @kodinkat !